### ISSUE TITLE
No Remote Futures Mailing List

### ISSUE THREAD

**Issue by ChrisCoffey** [DistributedRemoteFutures/DistributedRemoteFutures#76]
Hi guys, 

I spoke with Marvin on Wednesday about this project & I'm pretty intrigued by its potential. Could you guys set up a mailing list/ google group?

Thanks

**Comment by MartinSenne** [comment]
Hi Chris,

thanks for pointing that out. Please test, if you can post on
https://groups.google.com/forum/#!forum/remotefutures

Cheers,

Martin

**Comment by ChrisCoffey** [comment]
Thanks for creating this Martin. Unfortunately I'm unable to post on the group. Could you please review the settings?

**Comment by marvin-hansen** [comment]
Please try again chris

Marvin F. L. Hansen
+1 857-253-1982
www.marvin-hansen.tel
www.linkedin.com/in/marvinhansen
